### ISSUE TITLE
[calcon] minor bug in calibrated contrast when using single KLmode instead of list of multiple modes

### ISSUE THREAD

**Issue by raphhbw** [kammerje/spaceKLIP#119]
Seems to be a bug in the code after computing the inj-recovery in the calibrated contrast curves when using PSF subtracted images that have a single KLmode (e.g. [10]) and not a list of multiple KLmodes (e.g. [10,20]). I initially calculated the contrast for a ADI+RDI reduction only using a 10 KLmode which generated this error. When considering a list of [10,20] KL mode instead, the code ran fine.

Error was on this vstack on line 593 (check image linked) but now should be on line 619 (code has been changed since).

![Screenshot 2023-10-30 at 15 54 43](https://github.com/kammerje/spaceKLIP/assets/59627474/631bed42-1c32-49d2-9793-7fbfc9d968a3)

**Comment by mperrin** [comment]
@AarynnCarter can this issue be marked closed now? Fixed?
