### ISSUE TITLE
refactor/update make_psfsmasks

### ISSUE THREAD

**Issue by mperrin** [kammerje/spaceKLIP#122]
Some ideas that may improve functionality or robustness for handling the PSF masks. 

- [ ] When starting spaceKLIP, at import time check to see if PSF masks have been generated, and either automatically invoke make_psfmasks or pop up an alert message informing the user to do so. (I.e. similar to the WebbPSF data version check code)
- [ ] Include version information for PSF masks, since they rely on derived calibration information such as mask locations and filter shifts. We may want to force recomputing new versions of the psf masks after updates in that calibration information. 
- [ ] Optimize the list of which sets of filters and masks are iterated over for NIRCam. Currently it computes many impossible combinations using the SW filters for LW detector and vice versa (e.g. files like "NRCA2_MASK210R_F460M.fits"; you can't ever have F460M on NRCA2!)
- [ ] More major refactor: Rather than precomputing all masks, write code to compute on the fly just the ones that are needed, e.g. `get_psfmask('NRCA2', 'MASK210R', 'F200W') would either load that file from disk, or compute it and create that mask if it doesn't exist already.

**Comment by kammerje** [comment]
[This](https://github.com/kammerje/spaceKLIP/pull/117) PR implements pulling the PSF masks directly from CRDS as the new default. This is possible now because the masks were corrected on CRDS. I think it makes the above obsolete?

**Comment by mperrin** [comment]
I believe this issue has been addressed by #117 , since now the PSF masks are pulled from CRDS.
