### ISSUE TITLE
PA ranges bar causes error in current pipeline

### ISSUE THREAD

**Issue by AarynnCarter** [kammerje/spaceKLIP#13]
The current specification I have for the pa_ranges_bar in the config file causes an error when reading things in. 

`pa_ranges_bar: [(105.-15., 105.+15.), (285.-15., 285.+15.)]`

```
  File "/Users/acarter/Documents/DIRECT_IMAGING/CORONAGRAPHY_PIPELINE/TESTING/../pyKLIP_for_Webb/pyKLIP_for_Webb/io.py", line 34, in read_config
    pa_ranges_bar += [(float(temp[2*i][1:]), float(temp[2*i+1][:-1]))]
ValueError: could not convert string to float: '105.-15.'
```

This is a little bit of a strange way to input things, but I think we should also be able to grab the PA angle from the FITS headers. 

Also, it shouldn't be required for values to be provided, as it's only relevant for the bar mask.

**Comment by kammerje** [comment]
Yes, I can fix this, but I would like to keep it as a user input. At this point, it is totally unclear how big of a wedge should be chosen to compute the contrast limits for the bar mask, and I want to allow enough flexibility.
