### ISSUE TITLE
Bright pixels still present in simulated data

### ISSUE THREAD

**Issue by AarynnCarter** [kammerje/spaceKLIP#17]
I'm still seeing some bright pixels in the simulated data. @kammerje, do you think this is still a reference file issue or could it be to do with the updates to pyNRC? It significantly affects the contrast.

<img width="431" alt="Screen Shot 2022-04-08 at 4 30 42 PM" src="https://user-images.githubusercontent.com/23636747/162546337-394b3d8d-7dc5-4b79-9f53-63dc45c4d696.png">
<img width="813" alt="image" src="https://user-images.githubusercontent.com/23636747/162546427-c8f5a673-6159-4978-a347-c0fe87327ce8.png">

**Comment by kammerje** [comment]
If this was done with the new simulated data, then these are likely cosmic rays. The question is whether these cosmic rays are correctly flagged by the stage 1 pipeline. If so, we should be using a bad pixel cleaning algorithm before feeding the data into our pipeline. I have a simple [script](https://github.com/kammerje/spaceKLIP/files/8457182/preproc_pyklip.txt) if you are interested. If they are not flagged, then we need to tweak the stage 1 jump detection threshold I think.

**Comment by AarynnCarter** [comment]
Okay great, I'll try your script, I also might play around with adding an additional stage to start from the uncal.fits file. Does NIRCCos output those, or do we have to start with the rateints?

**Comment by kammerje** [comment]
Ok! NIRCCoS saves them in the pynrc_data folder.
