### ISSUE TITLE
[Bug]: pr-›orig_gdq is NULL.

### ISSUE THREAD

**Issue by ktcrotts** [kammerje/spaceKLIP#219]
### Check Existing Issues

- [X] Yes, I have checked existing issues to ensure this problem hasn't already been reported.

### Instrument or Category

NIRCam Stage 1/2 Pipeline

### Description

When running coron1pipeline.run_obs(), the error "pr-›orig_gdq is NULL." occurs unless "'algorithm': 'OLS'" is added under 'ramp_fit'.

<img width="890" alt="orig_gdq" src="https://github.com/user-attachments/assets/506f78ce-dcb8-42e2-b086-49fb3a266393">

### What operating system are you using?

Mac OS 14.7 Sonoma

### What version of Python are you running?

Python 3.11

**Comment by kglidic** [comment]
@ktcrotts Could you let us know what version of the jwst pipeline you were running with?

**Comment by mperrin** [comment]
I can confirm this works fine for me (no error) on pipeline 1.15.1, with no special handling or parameter set for the ramp fit algorithm.  i.e. using the default which is OLS_C now. 
In my case the conda env is installed via [stenv](https://stenv.readthedocs.io/en/latest/), not via spaceKLIP's requirements.txt.

**Comment by ktcrotts** [comment]
> @ktcrotts Could you let us know what version of the jwst pipeline you were running with?

I just looked and it says it's version 2.1.1.

**Comment by mperrin** [comment]
Hmm, that number doesn’t  make sense. We would expect `jwst.__version__` to be some value like “1.14.0” or “1.15.1” or “1.16.0”, but 1.16 is the current most recent.

**Comment by ktcrotts** [comment]
Oh sorry for the confusion I was looking at the version of SpaceKLIP. The version for jwst is 1.16.0.

**Comment by mperrin** [comment]
OK, thanks. That's very helpful:  I just confirmed that this _works on 1.15.1_ but _errors on 1.16.0_.  In the same conda environment so the only differences are the `jwst` version plus its `stcal` dependency (1.7.3 and 1.9.0, respectively)

**Comment by mperrin** [comment]
I'll followup with the pipeline developers to try to figure out what's up and how to fix it.

**Comment by mperrin** [comment]
Oh and FYI @kglidic, see my comment above. We probably want to, at least temporarily, put a note in the tutorial notebooks about needing to change this parameter with 1.16.0. 

Note, it's not enough to leave out the `maximum_cores` parameter. I tried that, but it turns out there's a [line of code in spaceKLIP](https://github.com/kammerje/spaceKLIP/blob/b9333b18dea33c72d7b630cc1434ca36f0ea32f0/spaceKLIP/coron1pipeline.py#L717) that sets the default to `'quarter'` if no value is provided for `maximum_cores`. This is an override for the default behavior in the `jwst` pipeline itself, for which the default is simple 1 (no multiprocessing).  So, for now it's necessary  to explicitly set the value to 1 when calling `coron1pipeline.run_obs`.

**Comment by JarronL** [comment]
I addressed this in a Slack message in the coronagraphy-pipeline channel a couple weeks ago. Set `maximum_cores='none'` during `run_obs` will solve the problem (has the same effect as Marshall's solution).

![image](https://github.com/user-attachments/assets/cd7cc8a0-9853-4b23-af85-917b85662c0b)

 I suggest we submit a PR with this is a the default in SpaceKLIP

e.g.,:
```python
    # Number of processor cores to use during ramp fitting process
    # 'none', 'quarter', 'half', or 'all'
    pipeline.ramp_fit.maximum_cores      = kwargs.get('maximum_cores', 'none')
```

https://github.com/kammerje/spaceKLIP/blob/6fa39c5f2afcc766bd66c0b667d81a21898c63b4/spaceKLIP/coron1pipeline.py#L717

**Comment by mperrin** [comment]
@ktcrotts might you be willing to make a pull request for this with the suggestion above from @JarronL, please ?  Simple edit for any of us to do; I'm mostly suggesting you simply as a tiny practice exercise now in PR'ing code changes into this repo for you, if you'd like.

**Comment by mperrin** [comment]
@ktcrotts never mind, Jarron's too fast 😆

**Comment by JarronL** [comment]
> @ktcrotts never mind, Jarron's too fast 😆

Oops!
