### ISSUE TITLE
link to sample data not working

### ISSUE THREAD

**Issue by douglase** [kammerje/spaceKLIP#22]
Hi, thanks for putting this project together! 

It looks like the Box simulated dataset link in the Readme is broken, at least from the outside, is there publicly available simulated data for testing?

**Comment by kammerje** [comment]
Thanks a lot for your feedback! It seems like the link is not public at the moment. Hopefully @AarynnCarter can help here.

**Comment by douglase** [comment]
Yes, I can see the folder now, thanks!
