### ISSUE TITLE
Upon code completion, many leaked semaphore objects

### ISSUE THREAD

**Issue by AarynnCarter** [kammerje/spaceKLIP#25]
Error message appears after running routines using pyKLIP's multiprocessing (e.g. PSF subtraction). Doesn't seem to be presenting any issues, and may well be part of the multiprocessing package itself. However, leaving this issue up in case anyone knows of a solution.

```
/Users/acarter/anaconda3/envs/sklip/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 64 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by mperrin** [comment]
Unclear if this is still an issue. Leaving this open.

**Comment by AarynnCarter** [comment]
Not seeing this any longer, will leave open a little while longer but we may be able to close this soon.
