### ISSUE TITLE
Artefacts seen in forward model PSFs at shorter wavelengths 

### ISSUE THREAD

**Issue by AarynnCarter** [kammerje/spaceKLIP#29]
Example below for NIRCam 335R with the F250M filter. Seems that the process of creating a forward model PSF, using an offaxis PSF model, doesn't work perfectly for shorter wavelengths where the PSFs are undersampled, producing ringing artefacts. Though is that this might be a result of the rotation / translation of the PSF within pyKLIP. 

Possible solutions:

1) See issue #26  about generating forward model PSFs at the correct location with webbpsf_ext. 

2) Oversample the model PSF prior to performing any pyKLIP translation/rotation, then degrade it at the end.

3) Apply a gaussian blur to the data and forward model, and proceed as normal. 

<img width="641" alt="image" src="https://user-images.githubusercontent.com/23636747/177386235-20b0cdb7-c8a8-4595-a0e2-872276bcda1e.png">

**Comment by kammerje** [comment]
From discussions with @semaphoreP and @AarynnCarter it seems like these artifacts do also appear from the spline interpolations used within `pyKLIP`. Hence, @AarynnCarter opted for blurring the undersampled data with a Gaussian. Should we make this a default in `spaceKLIP`?

**Comment by mperrin** [comment]
This was implemented in version 2. Fixed with blurring to avoid aliasing.
