### ISSUE TITLE
Fixing coronagraphic mask centers when applying coronagraphic mask transmission to raw contrast curves

### ISSUE THREAD

**Issue by kammerje** [kammerje/spaceKLIP#58]
@AarynnCarter modified the PSFMASK files to reflect the coronagraphic mask centers measured in flight. This change needs to be propagated through to @kammerje's application of the coronagraphic mask transmission to the raw contrast curves. For that, @AarynnCarter first needs to add header keywords specifying the new mask centers to the modified PSFMASK files.

**Comment by mperrin** [comment]
This was implemented in version 2.
