### ISSUE TITLE
Need to add image registration methodologies

### ISSUE THREAD

**Issue by AarynnCarter** [kammerje/spaceKLIP#7]
There are currently no methods to perform image registration / estimate relative offsets between images. 

Options include:

- Example code provided by Jason Wang (see slack)
- The jwst pipeline Stage 3 process (very memory intensive for a large number of integrations)
- Using gaia sources within images / subarrays to track relative offsets.  

Could also look at reducing computational intensity for these by average subsets of integrations (or all of them), or reducing the precision of values in the data arrays.

**Comment by kammerje** [comment]
@AarynnCarter Since this is handled by the JWST module of pyKLIP now, shall we close this issue?

**Comment by AarynnCarter** [comment]
Sounds good!
