### ISSUE TITLE
Make Jupyter notebooks for learning spaceKLIP

### ISSUE THREAD

**Issue by kammerje** [kammerje/spaceKLIP#75]
I have Python scripts to reduce the ERS data, but it would be nice to make Jupyter notebooks with a bit of text and explanations out of them for people to learn the new spaceKLIP.

**Comment by mperrin** [comment]
In progress now for the HIP 65426 data

**Comment by AarynnCarter** [comment]
Some notebooks are now available through the readthedocs. As this is quite a broad issue, I will close in lieu of us identifying more targeted issues.
