### ISSUE TITLE
I believe pysynphot is a requirement, but not listed in the requirements.txt

### ISSUE THREAD

**Issue by maxwellmb** [kammerje/spaceKLIP#88]
psf.py imports pysynphot, but it wasn't in the requirements. I'm not sure if this was on purpose, or not (pysynphot is weird...). In my experience pip worked better than conda (which downgraded a bunch of package installed for spaceklip).

**Comment by mperrin** [comment]
@AarynnCarter Same question, can this also be marked as completed now?
